name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v2
        with:
          terraform_version: latest
          terraform_wrapper: false
      - name: Check tf files
        run: |
          # run check formatting of files in tf-modules directory
          make tf-fmt TF_ARGS="-check -diff"
