name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v2
        with:
          terraform_version: latest
          terraform_wrapper: false
      - name: Check tf files
        run: |
          # run check formatting of files in tf-modules directory
          make tf-fmt TF_ARGS="-check -diff"
